# 소요시간
# [240503] : 10분

# ANIMAL_INS 테이블은 동물 보호소 동물 정보
# ANIMAL_OUTS 테이블은 동물 보호소에서 입양 보낸 동물의 정보를 담은 테이블

-- 코드를 입력하세요
SELECT ANIMAL_INS.ANIMAL_id, ANIMAL_INS.NAME FROM ANIMAL_INS
JOIN ANIMAL_OUTS
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_OUTS.DATETIME < ANIMAL_INS.DATETIME
ORDER BY ANIMAL_INS.DATETIME ASC;