# 도서들의 도서 정보(BOOK)
# 판매 정보(BOOK_SALES)

# 1. 2022년 1월의 카테고리 별 도서 판매량을 합산
# 2. 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력
# 3. 카테고리명을 기준으로 오름차순 정렬

-- 코드를 입력하세요
SELECT BOOK.CATEGORY, SUM(BOOK_SALES.SALES) AS TOTAL_SALES FROM BOOK_SALES
LEFT JOIN BOOK
ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
WHERE BOOK_SALES.SALES_DATE LIKE '2022-01-%'
GROUP BY BOOK.CATEGORY
HAVING SUM(BOOK_SALES.SALES)
ORDER BY CATEGORY ASC;


# SELECT * FROM BOOK_SALES;