# 소요시간
# [240503] : 정답참고

-- 코드를 입력하세요
SELECT ANIMAL_INS.ANIMAL_ID,ANIMAL_INS.ANIMAL_TYPE,ANIMAL_INS.NAME  FROM ANIMAL_OUTS
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_INS.SEX_UPON_INTAKE like 'Intact%' AND
    (ANIMAL_OUTS.SEX_UPON_OUTCOME like '%Neutered%' OR
     ANIMAL_OUTS.SEX_UPON_OUTCOME like '%Spayed%')
ORDER BY ANIMAL_INS.ANIMAL_ID ASC;


-- 코드를 입력하세요
SELECT ANIMAL_INS.ANIMAL_ID,ANIMAL_INS.ANIMAL_TYPE,ANIMAL_INS.NAME  FROM ANIMAL_OUTS
JOIN ANIMAL_INS
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_INS.SEX_UPON_INTAKE like 'Intact%'
  AND ANIMAL_OUTS.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY ANIMAL_INS.ANIMAL_ID ASC;